### ISSUE TITLE
似乎无法通过脚手架下载？

### ISSUE THREAD

**Issue by Moekey114514** [dpm12345/nonebot_plugin_tts_gal#1]
![image](https://user-images.githubusercontent.com/48763754/191204384-f8cd4eb8-93ff-496c-afb0-84fb28cb1900.png)

**Comment by dpm12345** [comment]
nb商店暂时还没有上架，请先使用pip

**Comment by dpm12345** [comment]
> ![image](https://user-images.githubusercontent.com/48763754/191204384-f8cd4eb8-93ff-496c-afb0-84fb28cb1900.png)

nb商店目前还未上架，pip请检查本地网络，我这边是可以连接到的

**Comment by Moekey114514** [comment]
确实通过pip成功连上了，不过可能是由于我python3.9.13的原因没法正常下载
![image](https://user-images.githubusercontent.com/48763754/191215778-01b62551-decf-4794-b060-9ea78a3fd589.png)

**Comment by Moekey114514** [comment]
我再想想办法吧，应该是本地环境的原因

**Comment by dpm12345** [comment]
> 我再想想办法吧，应该是本地环境的原因

这个问题我在测试时也遇到过，之后我写一下解决方案吧

**Comment by JHXAloha** [comment]
> 

后面怎么解决的嘞
