### ISSUE TITLE
pip下载后data文件夹里没有出现插件

### ISSUE THREAD

**Issue by 19231224lhr** [dpm12345/nonebot_plugin_tts_gal#10]
不知道怎么回似
![image](https://user-images.githubusercontent.com/70199004/196668281-3971447b-72b2-4ff8-9212-7794243719de.png)
![image](https://user-images.githubusercontent.com/70199004/196668333-61e86826-0544-45c2-9db5-d70fd9a35c12.png)
python插件是有的
![image](https://user-images.githubusercontent.com/70199004/196668486-1e3753f9-6537-42c6-9e51-fbeee3e5412b.png)

**Comment by dpm12345** [comment]
> 不知道怎么回似 ![image](https://user-images.githubusercontent.com/70199004/196668281-3971447b-72b2-4ff8-9212-7794243719de.png) ![image](https://user-images.githubusercontent.com/70199004/196668333-61e86826-0544-45c2-9db5-d70fd9a35c12.png) python插件是有的 ![image](https://user-images.githubusercontent.com/70199004/196668486-1e3753f9-6537-42c6-9e51-fbeee3e5412b.png)

这个运行之后会创建的，然后根据我写的添加对应文件

**Comment by 19231224lhr** [comment]
> > 不知道怎么回似 ![image](https://user-images.githubusercontent.com/70199004/196668281-3971447b-72b2-4ff8-9212-7794243719de.png) ![image](https://user-images.githubusercontent.com/70199004/196668333-61e86826-0544-45c2-9db5-d70fd9a35c12.png) python插件是有的 ![image](https://user-images.githubusercontent.com/70199004/196668486-1e3753f9-6537-42c6-9e51-fbeee3e5412b.png)
> 
> 这个运行之后会创建的，然后根据我写的添加对应文件

呜呜，但是运行后报错说`'Config' object has no attribute 'auto_delete_voice'`

![image](https://user-images.githubusercontent.com/70199004/196670763-10463c4f-138d-40e8-8b2a-eb29f4919bd6.png)

**Comment by dpm12345** [comment]
在你的配置文件`.env.*`里添加`auto_delete_voice = true`

这些在我主页上的readme.md有写的，可以先看一下

**Comment by 19231224lhr** [comment]
> 在你的配置文件`.env.*`里添加`auto_delete_voice = true`
> 
> 这些在我主页上的readme.md有写的，可以先看一下

好的，谢谢大佬
