### ISSUE TITLE
未配置auto_delete_voice项,将默认为true

### ISSUE THREAD

**Issue by lancer-wang** [dpm12345/nonebot_plugin_tts_gal#11]
![image](https://user-images.githubusercontent.com/69783837/197127953-f865c9ac-6e0e-453f-a07b-1740dc2fea83.png)
![image](https://user-images.githubusercontent.com/69783837/197128107-247f1bdb-211a-4705-beb6-c997807a69be.png)

原因不明
ubuntu20
python3.10版本

**Comment by dpm12345** [comment]
请问是在.env.*配置文件中设置的吗

**Comment by lancer-wang** [comment]
> 请问是在.env.*配置文件中设置的吗

是的,
下面的tts_gal  是可以用的

**Comment by dpm12345** [comment]
> > 请问是在.env.*配置文件中设置的吗
> 
> 是的, 下面的tts_gal 是可以用的

我发现是我判断写错了，等会我改一下

**Comment by dpm12345** [comment]
已经更新了 @lancer-wang

**Comment by lancer-wang** [comment]
现在可以了
