### ISSUE TITLE
插件启动报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [dpm12345/nonebot_plugin_tts_gal#12]
from .htsengine import HTSEngine
File "pyopenjtalk/htsengine.pyx", line 1, in init pyopenjtalk.htsengine
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
不太清楚是咋回事

**Comment by ElainaFanBoy** [comment]
草，我把numpy更新了一下就好了，已解决

**Comment by dpm12345** [comment]
之前是什么版本，我看看是否确实需要改一下依赖

> 草，我把numpy更新了一下就好了，已解决

**Comment by ElainaFanBoy** [comment]
> 之前是什么版本，我看看是否需要改一下依赖
> 
> > 草，我把numpy更新一下就好了，已经解决了

我也忘记了！很久没有更新过，没看版本就直接重装了一下numpy就好了
