### ISSUE TITLE
亚托莉语音报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [dpm12345/nonebot_plugin_tts_gal#13]
AttributeError: module 'src.plugins.nonebot_plugin_tts_gal.text.cleaners' has no attribute 'custom_cleaners'

只有亚托莉的语音报错，其它的没问题，不知道咋回事

**Comment by dpm12345** [comment]
> AttributeError: module 'src.plugins.nonebot_plugin_tts_gal.text.cleaners' has no attribute 'custom_cleaners'
> 
> 只有亚托莉的语音报错，其它的没问题，不知道咋回事

这个我在我的readme.md和usage.md作出了说明，算是0.3.0版本一个比较大的改动，可以看一下

**Comment by dpm12345** [comment]
> AttributeError: module 'src.plugins.nonebot_plugin_tts_gal.text.cleaners' has no attribute 'custom_cleaners'
> 
> 只有亚托莉的语音报错，其它的没问题，不知道咋回事

可以在模型的`text_cleaners`项将`custom_cleaners`直接改为`japanese_cleaners`

**Comment by dpm12345** [comment]
> > AttributeError: module 'src.plugins.nonebot_plugin_tts_gal.text.cleaners' has no attribute 'custom_cleaners'
> > 只有亚托莉的语音报错，其它的没问题，不知道咋回事
> 
> 可以在模型的`text_cleaners`项将`custom_cleaners`直接改为`japanese_cleaners`

json配置文件里

**Comment by ElainaFanBoy** [comment]
> > AttributeError: module 'src.plugins.nonebot_plugin_tts_gal.text.cleaners' has no attribute 'custom_cleaners'
> > 
> > 只有亚托莉的语音报错，其它的没问题，不知道咋回事
> 
> 可以在模型的`text_cleaners`项将`custom_cleaners`直接改为`japanese_cleaners`

刚看文档了，已经修改（辛苦了！）
