### ISSUE TITLE
原模型data项里的text_cleaners内不是japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2

### ISSUE THREAD

**Issue by AtoriUzawa** [dpm12345/nonebot_plugin_tts_gal#14]
原模型data项里的text_cleaners内不是japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2之一
而是custom_cleaners，需要改成哪一个，或者japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2有什么不同？
本人小白，菜菜，大佬帮帮忙(。・ω・。)

**Comment by dpm12345** [comment]
> 原模型data项里的text_cleaners内不是japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2之一 而是custom_cleaners，需要改成哪一个，或者japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2有什么不同？ 本人小白，菜菜，大佬帮帮忙(。・ω・。)

日语语音的话你就选japanese的就行了，2个效果一样的，中文就选chinese，如果都不是，可以为我提供原项目代码，我试着在之后的版本添加上去

**Comment by AtoriUzawa** [comment]
谢谢谢大佬
&nbsp;


…
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 上午9:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dpm12345/nonebot_plugin_tts_gal] 原模型data项里的text_cleaners内不是japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2 (Issue #14)



原模型data项里的text_cleaners内不是japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2之一 而是custom_cleaners，需要改成哪一个，或者japanese_cleaners ，japanese_cleaners2 ，chinese_cleaners2有什么不同？ 本人小白，菜菜，大佬帮帮忙(。・ω・。)
  日语语音的话你就选japanese的就行了，2个效果一样的，中文就选chinese，如果都不是，可以为我提供原项目代码，我试着在之后的版本添加上去
