### ISSUE TITLE
导入模型之后回复模型加载失败

### ISSUE THREAD

**Issue by yukina0217** [dpm12345/nonebot_plugin_tts_gal#16]
![image](https://user-images.githubusercontent.com/116873037/199683008-40fcf49b-cacb-4efa-9b9b-d177e3aea06f.png)
报错信息如上 因为自己太菜了 百度搜到可以忽略这个但是还是完全不会 教程中的yuzusoft和atri都可以使用 没有别的问题 求教

**Comment by dpm12345** [comment]
这个应该是由于目前你的模型配置文件的symbols和模型文件不匹配，看看是不是用的原作者的symbols

**Comment by yukina0217** [comment]
原作者没有symbols

**Comment by dpm12345** [comment]
> 原作者没有symbols

用的是哪个作者的模型

**Comment by yukina0217** [comment]
用的是pjsk-gui中的模型，地址为https://github.com/Kanade-nya/PJSK-MultiGUI

**Comment by yukina0217** [comment]
![image](https://user-images.githubusercontent.com/116873037/199684817-338e7a47-03bd-4d0e-9f5f-f9d29bec9302.png)
json是这样的，language开始都是我复制您的json下的。。。

**Comment by dpm12345** [comment]
symbols不同作者训练时会有差别，这个和其他的配置不一样

**Comment by yukina0217** [comment]
请问有什么解决办法吗

**Comment by dpm12345** [comment]
找原作者要一下symbols吧

**Comment by yukina0217** [comment]
好的 麻烦您进行解答这个比较蠢的问题了 非常感谢
