### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by yoiyami96** [dpm12345/nonebot_plugin_tts_gal#2]
有道的翻译质量不是很理想，能否换成谷歌或腾讯翻译

**Comment by dpm12345** [comment]
> 有道的翻译质量不是很理想，能否换成谷歌或腾讯翻译

可以考虑，我在之后版本进行添加修改吧

**Comment by Agnes4m** [comment]
提议用百度翻译，自己填写id和key的形式（作为一个可选项）

**Comment by dpm12345** [comment]
已经新增了百度翻译和腾讯翻译的API选项
