### ISSUE TITLE
提议：在PicMenu插件中加入二级菜单

### ISSUE THREAD

**Issue by Agnes4m** [dpm12345/nonebot_plugin_tts_gal#21]
### 就是此插件的二级菜单效果是这样的
![image](https://user-images.githubusercontent.com/70925546/206636817-7b9a38c3-9de0-4464-9278-3e93f491dcc3.png)
### 我希望的就是能在二级菜单中，显示现有的模型，比如nonebot-plugin-random插件的效果，每一个新加的功能都能在二级菜单显示
![image](https://user-images.githubusercontent.com/70925546/206637140-c033dbae-7a81-4f3a-b7ad-ac3845a4f696.png)
链接在下面
[https://github.com/jcjrobert/nonebot-plugin-random](url)

**Comment by dpm12345** [comment]
已经添加了
