### ISSUE TITLE
加载成功却无法响应？

### ISSUE THREAD

**Issue by Agnes4m** [dpm12345/nonebot_plugin_tts_gal#24]
### 菜单 5指令下，正确加载了，并返回了模型的指令图片（启动nb端时也正常加载没有报错）
![image](https://user-images.githubusercontent.com/70925546/206912429-206a08c9-afb3-411f-a069-cdd0c072c0a3.png)

### 但是用指令却没有响应（我之前用的2.0版本的，虽然最近才更新由于用的少也没注意到这个问题）也没有报错
`12-11 23:21:17 [SUCCESS] nonebot | OneBot V11 2711142767 | [message.group.normal]: Message -1611947915 from 735803792@[群:674602274] "/宁宁说こんにちは"`

env设置（直接复制的）
```
tts_gal = '{
    ("宁宁", "绫地宁宁"): ["YuzuSoft",0],
    ("因幡爱瑠", "爱瑠"): ["YuzuSoft",1],
    ("朝武芳乃", "芳乃"): ["YuzuSoft",2],
    ("常陸茉子", "茉子"): ["YuzuSoft",3],
    ("丛雨", "幼刀"): ["YuzuSoft",4],
    ("鞍馬小春", "鞍马小春", "小春"): ["YuzuSoft",5],
    ("在原七海", "七海"): ["YuzuSoft",6],
    ("ATRI", "atri", "亚托莉"): ["ATRI"],
    ("和泉妃爱","妃爱"): ["fupomei",0],
    ("常盤華乃","常盘华乃","华乃"): ["fupomei",1],
    ("錦あすみ","锦亚澄"): ["fupomei",2],
    ("鎌倉詩桜","镰仓诗樱"): ["fupomei",3],
    ("竜閑天梨","龙闲天梨","天梨"): ["fupomei",4],
    ("和泉里",): ["fupomei",5],
    ("新川広夢","新川广梦"): ["fupomei",6],
    ("聖莉々子","圣莉莉子"): ["fupomei",7],
}'
```
顺便说下配置，python3.9.15,ubuntu20.04,nonebot2.0.0rc1，文件也放正确的位置了并改相同大多名字

**Comment by dpm12345** [comment]
应该是不用`/`的，这个不是命令

**Comment by dpm12345** [comment]
也不会回复"暂时未有该角色"吗？

**Comment by Agnes4m** [comment]
没有前缀也试过了，就是什么也没回复，也检查nickname没有冲突了

**Comment by dpm12345** [comment]
会不会是少了`@`？

**Comment by dpm12345** [comment]
可能阻断之类的？
方便的话给个完整的信息

**Comment by Agnes4m** [comment]
确定了原因是没有艾特。。。因为艾特我设置了其他的智能回复，一时没想到。。。希望env里可以可选设置是否需要艾特（我自己先删了）
