### ISSUE TITLE
nb安装时报错，大佬帮我康康

### ISSUE THREAD

**Issue by MoKeNeng** [dpm12345/nonebot_plugin_tts_gal#26]
![1](https://user-images.githubusercontent.com/117900223/207238430-552657b2-cf23-469a-8b8b-f0d9589d9de5.png)

**Comment by dpm12345** [comment]
可以参考我在`README.md`中写的关于`pyopenjtalk`的解决方法

**Comment by MoKeNeng** [comment]
参考README.md，下载了cmake，一个三角形图标的软件。之后还是报错
![2](https://user-images.githubusercontent.com/117900223/207241344-cfbdbedc-9703-4a27-adc4-f1539deee9b3.png)

**Comment by dpm12345** [comment]
应该是`cmake`版本过低，我用的**3.25.1**可以正常安装

**Comment by MoKeNeng** [comment]
我也是3.25.1

**Comment by dpm12345** [comment]
更新一下`Cython`版本？

**Comment by MoKeNeng** [comment]
python是3.9的

**Comment by MoKeNeng** [comment]
cmake是不是要搞个C语音的环境？

**Comment by dpm12345** [comment]
是的，你可以参考`README.md`中的VS2022进行下载

**Comment by MoKeNeng** [comment]
累了，毁灭吧，还要用C运行的吗
