### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xd1'.

### ISSUE THREAD

**Issue by Loss-of-time** [dpm12345/nonebot_plugin_tts_gal#28]
![image](https://user-images.githubusercontent.com/51469672/211816982-52921672-6928-4185-a1c6-8398c5c77da9.png)

环境：腾讯云轻量应用服务器，UbuntuLTSC2022
使用的模型为默认的柚子社多人模型，在本人的windows环境下该模型及配置文件可以正常工作。

**Comment by dpm12345** [comment]
既然你在本地跑是正常的，那么照理说服务器上也是行的
你可以检查一下配置是否弄错，文件是否上传错误
可以的话，可以提供一下服务器的环境信息

**Comment by Loss-of-time** [comment]
邪门
重新上传一遍又能跑了
