### ISSUE TITLE
tts_gal_is_at = False和true都换着添了。还是需要在群at，是我添加格式不对吗？

### ISSUE THREAD

**Issue by tsai-xy** [dpm12345/nonebot_plugin_tts_gal#29]
auto_delete_voice = False
tts_gal_is_at = False
tts_gal = '{
    ("宁宁", "绫地宁宁"): ["YuzuSoft",0],
    ("因幡爱瑠", "爱瑠"): ["YuzuSoft",1],
    ("朝武芳乃", "芳乃"): ["YuzuSoft",2],
    ("常陸茉子", "茉子"): ["YuzuSoft",3],
    ("丛雨", "幼刀"): ["YuzuSoft",4],
    ("鞍馬小春", "鞍马小春", "小春"): ["YuzuSoft",5],
    ("在原七海", "七海"): ["YuzuSoft",6],
    ("atri", "atri"): ["ATRI",0],
    ("杏璃", "鹰仓杏璃"): ["tts13",0],
    ("杏铃", "鹰仓杏铃"): ["tts13",1],
    ("Apeiria", "艾佩理雅"): ["tts13",2],
    ("明日香"): ["tts13",3],
    ("艾拉酱", "艾拉"): ["tts13",5],
    ("彩音"): ["tts13",6],
    ("星奏", "Sena"): ["tts13",7],
    ("由依"): ["tts13",8],
    ("圣代桥冰织", "冰织"): ["tts13",9],
    ("椎名真白", "真白"): ["tts13",10],
    ("美绘瑠"): ["tts13",11],
    ("真红", "二阶堂真红"): ["tts13",12],
    ("茉莉"): ["mori",0],
}'

**Comment by dpm12345** [comment]
试试改为`false`?

**Comment by dpm12345** [comment]
日志信息有吗？

**Comment by tsai-xy** [comment]
![8RPNM4WO QUND)%MF@)(B}U](https://user-images.githubusercontent.com/118656253/212286903-c42a2446-d691-4d38-96aa-532ad1b007c0.png)
![8JL5DXMUIXTSPLP G480 I1](https://user-images.githubusercontent.com/118656253/212286913-620ffee1-9c96-4aa6-923b-96d6671c9e7b.png)
控制台看着像不@就是单纯没反应

**Comment by dpm12345** [comment]
用的是最新的版本的吧

**Comment by tsai-xy** [comment]
才装几天，应该是最新的吧。 才玩nb2不知道更新命令 脚手架安装的

**Comment by dpm12345** [comment]
`pip show nonebot_plugin_tts_gal`看一眼

**Comment by tsai-xy** [comment]
解决了

**Comment by tsai-xy** [comment]
谢谢佬
