### ISSUE TITLE
local variable 'hps_ms' referenced before assignment

### ISSUE THREAD

**Issue by MoYoez** [dpm12345/nonebot_plugin_tts_gal#3]
![image](https://user-images.githubusercontent.com/30306672/192126528-35ed7b0a-2bc2-4513-858d-e3a6c1e4003b.png)
搭建的时候出的问题(

**Comment by dpm12345** [comment]
> ![image](https://user-images.githubusercontent.com/30306672/192126528-35ed7b0a-2bc2-4513-858d-e3a6c1e4003b.png) 搭建的时候出的问题(

配置文件下载了吗

**Comment by MoYoez** [comment]
> > ![image](https://user-images.githubusercontent.com/30306672/192126528-35ed7b0a-2bc2-4513-858d-e3a6c1e4003b.png) 搭建的时候出的问题(
> 
> 配置文件下载了吗

a ( 没看到 抱歉抱歉(

可以稍微改进一下 读取时未找到进行下载(
