### ISSUE TITLE
openjtalk安装问题

### ISSUE THREAD

**Issue by tianyisama** [dpm12345/nonebot_plugin_tts_gal#33]
使用语音合成时，会自动开始下载openjtalk，但是无法连接：urllib.error.HTTPError: HTTP Error 502: Bad Gateway
如果使用代理，则有道和百度等翻译则会显示无法使用： <class 'httpx.ConnectError'>，请问有无解决办法

**Comment by dpm12345** [comment]
你可以试试`pip install openjtalk`，我记得效果是一样的

**Comment by tianyisama** [comment]
> 你可以试试`pip install openjtalk`，我记得效果是一样的

我尝试了使用pip安装，但是仍然有相同报错
![image](https://user-images.githubusercontent.com/118712549/222913720-f8eaca1d-a118-43eb-ad13-7e78c490d4a6.png)

**Comment by dpm12345** [comment]
> > 你可以试试`pip install openjtalk`，我记得效果是一样的
> 
> 我尝试了使用pip安装，但是仍然有相同报错 ![image](https://user-images.githubusercontent.com/118712549/222913720-f8eaca1d-a118-43eb-ad13-7e78c490d4a6.png)

这样，你先把插件目录下的`__init__.py`第82行注释掉，取消翻译，然后开启代理，并生成一段语音
成功完成这一过程后，然后再取消注释，关闭代理

**Comment by tianyisama** [comment]
> > > 你可以试试`pip install openjtalk`，我记得效果是一样的
> > 
> > 
> > 我尝试了使用pip安装，但是仍然有相同报错 ![image](https://user-images.githubusercontent.com/118712549/222913720-f8eaca1d-a118-43eb-ad13-7e78c490d4a6.png)
> 
> 这样，你先把插件目录下的`__init__.py`第82行注释掉，取消翻译，然后开启代理，并生成一段语音 成功完成这一过程后，然后再取消注释，关闭代理

取消掉注释后仍然无法跳过连接翻译出错，看起来似乎不起作用，请问还有哪些地方的注释需要更改吗。另外我尝试了给框架安装了GitHub适配器，但是总是下到一定程度就会掉线，而且10kb/s的速度真是折磨

**Comment by dpm12345** [comment]
我这里想到的是先本地下载`https://github.com/r9y9/open_jtalk/releases/download/v1.11.1/open_jtalk_dic_utf_8-1.11.tar.gz`的压缩包文件，然后解压，将解压后的文件夹放到`pyopenjtalk`的包目录下，然后再发送命令

**Comment by dpm12345** [comment]
> 我这里想到的是先本地下载`https://github.com/r9y9/open_jtalk/releases/download/v1.11.1/open_jtalk_dic_utf_8-1.11.tar.gz`的压缩包文件，然后解压，将解压后的文件夹放到`pyopenjtalk`的包目录下，然后再发送命令
或者是这个链接`https://ghproxy.com/https://github.com/r9y9/open_jtalk/releases/download/v1.11.1/open_jtalk_dic_utf_8-1.11.tar.gz`

**Comment by dpm12345** [comment]
又或者将该原包中`__init__.py`的第30行代码
`_dict_download_url = "https://github.com/r9y9/open_jtalk/releases/download/v1.11.1"`
直接修改为
`_dict_download_url = "https://ghproxy.com/https://github.com/r9y9/open_jtalk/releases/download/v1.11.1"`
改善下载速度
