### ISSUE TITLE
 unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by 34gram** [dpm12345/nonebot_plugin_tts_gal#37]
大佬您好，请问这个错误怎么解决？
![QQ图片20230322174305](https://user-images.githubusercontent.com/128144203/226863710-86f2cda9-6a3c-4168-b316-e2cf5265fda9.png)

**Comment by dpm12345** [comment]
配置里的模型名字是不是忘加引号了？

**Comment by 34gram** [comment]
感谢回复!!!
我下了自习就去看看

**Comment by 34gram** [comment]
检查了，有
试着重启了bot，还是不行
![QQ图片20230322200800](https://user-images.githubusercontent.com/128144203/226900715-fbd5791d-e75c-4cdd-9ed2-bacc0194a4c8.png)

**Comment by dpm12345** [comment]
> 检查了，有 试着重启了bot，还是不行 ![QQ图片20230322200800](https://user-images.githubusercontent.com/128144203/226900715-fbd5791d-e75c-4cdd-9ed2-bacc0194a4c8.png)

你的配置有问题，最后三个角色少了其对应的模型名和配置名，具体可以看`Usage.md`的内容

**Comment by 34gram** [comment]
好的，解决了谢谢
