### ISSUE TITLE
好像与nonebot2 rc4版本不兼容

### ISSUE THREAD

**Issue by Ealvn** [dpm12345/nonebot_plugin_tts_gal#39]
在使用最近更新的nonebot2 rc4版本与tts_gal最新版时启动失败，从报错中可以看出问题好像出在init中检查目录、配置时：
https://github.com/dpm12345/nonebot_plugin_tts_gal/blob/61a972010fb4edc75b2275f8a6cf0241b39403e0/nonebot_plugin_tts_gal/__init__.py#L62
测试回滚nonebot2到rc3版本或跳过目录配置检查后，可正常启动
报错截图：
![image](https://user-images.githubusercontent.com/39033468/230767742-0f5564d0-b5ef-4ed4-86c4-58d3a6c4337d.png)

**Comment by dpm12345** [comment]
估计是我之前写法的问题，可以将`__init__.py`的`@driver.on_startup`下一行的`def`改为`async def`

**Comment by dpm12345** [comment]
我之后更新
