### ISSUE TITLE
能不能做到改成不at机器人就能触发指令

### ISSUE THREAD

**Issue by CCYellowStar** [dpm12345/nonebot_plugin_tts_gal#4]

**Comment by dpm12345** [comment]
> _No description provided._

如果改成不at的话，机器人会对每一个“xxx说xxx”进行匹配，我认为会造成不必要匹配情况

**Comment by dpm12345** [comment]
> _No description provided._

如果改成不at的话，机器人会对每一个“xxx说xxx”进行匹配，我认为会造成不必要匹配情况

如果你可以接受这种情况，可以自行在下载的包列表中，找到depends.py文件，将22、23行的语句删掉
```
if isinstance(event,GroupMessageEvent) and not event.is_tome():
    return False
```

**Comment by CCYellowStar** [comment]
好吧，一般这个规则都是写在命令触发函数里的，原来你写其他地方去了
