### ISSUE TITLE
安装报错，不太清楚是什么原因

### ISSUE THREAD

**Issue by NAOLIU** [dpm12345/nonebot_plugin_tts_gal#44]
这是我第一次失败执行pip install，第二次执行的样子：

PS C:\Users\Administrator> pip install nonebot_plugin_tts_gal --user
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\administrator\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\administrator\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting nonebot_plugin_tts_gal
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/50/17/b0b0116c9f55b33a57c7a6a750eb5511b064d8a95202cc629c3080b3ed6f/nonebot_plugin_tts_gal-0.3.11-py3-none-any.whl (1.2 MB)
Collecting ffmpy<0.4.0,>=0.3.0 (from nonebot_plugin_tts_gal)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bf/e2/947df4b3d666bfdd2b0c6355d215c45d2d40f929451cb29a8a2995b29788/ffmpy-0.3.0.tar.gz (4.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting httpx<0.24.0,>=0.23.1 (from nonebot_plugin_tts_gal)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ac/a2/0260c0f5d73bdf06e8d3fc1013a82b9f0633dc21750c9e3f3cb1dba7bb8c/httpx-0.23.3-py3-none-any.whl (71 kB)
Collecting janome<0.5.0,>=0.4.2 (from nonebot_plugin_tts_gal)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2b/09/99a267382d699766366419773c2ef09e2dc4a033a4c48cc31b26bd509b04/Janome-0.4.2-py2.py3-none-any.whl (19.7 MB)
Requirement already satisfied: jieba<0.43.0,>=0.42.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from nonebot_plugin_tts_gal) (0.42.1)
Requirement already satisfied: nonebot-adapter-onebot<3.0.0,>=2.1.1 in c:\users\administrator\appdata\roaming\python\python310\site-packages (from nonebot_plugin_tts_gal) (2.2.3)
Requirement already satisfied: nonebot-plugin-apscheduler<0.3.0,>=0.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from nonebot_plugin_tts_gal) (0.2.0)
Requirement already satisfied: nonebot2<3.0.0,>=2.0.0b4 in c:\users\administrator\appdata\roaming\python\python310\site-packages (from nonebot_plugin_tts_gal) (2.0.0rc4)
Collecting numba<0.57.0,>=0.56.2 (from nonebot_plugin_tts_gal)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fa/a1/e9dad5793d45f08401aa6983a93d53423ce4a403ae333937fa2448b263b2/numba-0.56.4-cp310-cp310-win_amd64.whl (2.5 MB)
Requirement already satisfied: numpy<2.0.0,>=1.20.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from nonebot_plugin_tts_gal) (1.22.2)
Collecting pyopenjtalk<0.4.0,>=0.3.0 (from nonebot_plugin_tts_gal)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b4/80/a2505a37937fcd108b7c1ab66f7d1d48560525b1da71993860d11095a286/pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-hz34eadv\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-hz34eadv\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-hz34eadv\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-hz34eadv\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\administrator\appdata\roaming\python\python310\site-packages)

**Comment by dpm12345** [comment]
这个https://github.com/dpm12345/nonebot_plugin_tts_gal#-qa
参考过了吗？

**Comment by NAOLIU** [comment]
> 这个https://github.com/dpm12345/nonebot_plugin_tts_gal#-qa 参考过了吗？

试过了，还是一样
![image](https://github.com/dpm12345/nonebot_plugin_tts_gal/assets/55797625/d517350a-118a-4ad6-aa79-8cfc9c9bd5e1)
也正确地加入到环境变量了
![image](https://github.com/dpm12345/nonebot_plugin_tts_gal/assets/55797625/31b166a5-aeee-476b-bc6f-65be6bed8cea)
openjtalk也单独装过了
