### ISSUE TITLE
“亚托莉”无法触发

### ISSUE THREAD

**Issue by AtoriUzawa** [dpm12345/nonebot_plugin_tts_gal#6]
在.env.*配置项已加入

auto_delete_voice = False
tts_gal = '{
	("ATRI","atri","亚托莉","老婆","萝卜子"):["ATRI"],
}'

使用“亚托莉”时无法触发，其他都可以正常触发
且其他插件都没有进行阻断

**Comment by dpm12345** [comment]
> 在.env.*配置项已加入
> 
> auto_delete_voice = False tts_gal = '{ ("ATRI","atri","亚托莉","老婆","萝卜子"):["ATRI"], }'
> 
> 使用“亚托莉”时无法触发，其他都可以正常触发 且其他插件都没有进行阻断

我在我这边是可以使用这个关键词的，你看看是不是输入错误了，或者你也可以把运行截图发一下(
照理来说既然其他可以用，那么`亚托莉`也可以用的

**Comment by AtoriUzawa** [comment]
我好像知道为啥了，但是不知道咋解决，在收到信息的时候自动把“亚托莉去掉了”

09-30 23:29:54 [SUCCESS] nonebot | ONEBOT V11 2177037109 | [message.group.normal]: Message 638661070 from 3230772278@[群:1169715079] "说喜欢"
09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_bilibili_viode.main, type=message, priority=1, temp=False>
09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_bilibili_viode.main, type=message, priority=1, temp=False> running complete
09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from atri.plugins.随机图片, type=message, priority=1, temp=False>
09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from atri.plugins.随机图片, type=message, priority=1, temp=False> running complete
09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False>
09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False> running complete
09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from atri.plugins.nonebot_plugin_kawaii_robot-master, type=message, priority=100, temp=False>
09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from atri.plugins.nonebot_plugin_kawaii_robot-master, type=message, priority=100, temp=False> running complete

**Comment by dpm12345** [comment]
> 

我稍微测试了一下，可能是这个原因

你的机器人配置中`nickname`是否也有`亚托莉`？我在测试时，如果出现`nickname`中的词，那么机器人好像也是视为被@了,然后`亚托莉j

**Comment by dpm12345** [comment]
> 我好像知道为啥了，但是不知道咋解决，在收到信息的时候自动把“亚托莉去掉了”
> 
> 09-30 23:29:54 [SUCCESS] nonebot | ONEBOT V11 2177037109 | [message.group.normal]: Message 638661070 from 3230772278@[群:1169715079] "说喜欢" 09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_bilibili_viode.main, type=message, priority=1, temp=False> 09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_bilibili_viode.main, type=message, priority=1, temp=False> running complete 09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from atri.plugins.随机图片, type=message, priority=1, temp=False> 09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from atri.plugins.随机图片, type=message, priority=1, temp=False> running complete 09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False> 09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False> running complete 09-30 23:29:54 [INFO] nonebot | Event will be handled by <Matcher from atri.plugins.nonebot_plugin_kawaii_robot-master, type=message, priority=100, temp=False> 09-30 23:29:54 [INFO] nonebot | Matcher <Matcher from atri.plugins.nonebot_plugin_kawaii_robot-master, type=message, priority=100, temp=False> running complete

我稍微测试了一下，可能是这个原因

你的机器人配置中nickname是否也有亚托莉？我在测试时，如果出现nickname中的词，那么机器人好像也是视为被@了,然后消息中`亚托莉`会被去掉

你看看是不是这个原因，如果还不行，我就无能为力了

**Comment by AtoriUzawa** [comment]
是的nickname是“亚托莉”，大佬可以找到原因吗[doge]&nbsp;


…
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月30日(星期五) 晚上11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dpm12345/nonebot_plugin_tts_gal] “亚托莉”无法触发 (Issue #6)





   
我稍微测试了一下，可能是这个原因
 
你的机器人配置中nickname是否也有亚托莉？我在测试时，如果出现nickname中的词，那么机器人好像也是视为被@了,然后`亚托莉j

**Comment by dpm12345** [comment]
> 是的nickname是“亚托莉”，大佬可以找到原因吗[doge]&nbsp; … ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月30日(星期五) 晚上11:51 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [dpm12345/nonebot_plugin_tts_gal] “亚托莉”无法触发 (Issue #6) 我稍微测试了一下，可能是这个原因 你的机器人配置中nickname是否也有亚托莉？我在测试时，如果出现nickname中的词，那么机器人好像也是视为被@了,然后`亚托莉j — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

在官方文档中是这样对`Nickname`项描述的

![HO% 0IVI{$PG1L_0MGP)5AL](https://user-images.githubusercontent.com/89716406/193310783-4c3a1490-f670-4dc8-8e9a-f826261bc31b.png)

由于设置的关键词与`nickname`冲突，造成认为是@，不是当前rule匹配的消息内容中

如果在不改变`nickname`的情况下，目前我能想到的就是重写`rule`方法
