### ISSUE TITLE
我在尝试为nonebot_plugin_tts_gal添加中文模型的时候遇到了【加载模型失败】错误，添加日文模型是正常的。

### ISSUE THREAD

**Issue by dispina** [dpm12345/nonebot_plugin_tts_gal#9]
tts_gal = '{
    ("宁宁", "绫地宁宁"): ["YuzuSoft",0],
    ("因幡爱瑠", "爱瑠"): ["YuzuSoft",1],
    ("朝武芳乃", "芳乃"): ["YuzuSoft",2],
    ("常陸茉子", "茉子"): ["YuzuSoft",3],
    ("丛雨", "幼刀"): ["YuzuSoft",4],
    ("鞍馬小春", "鞍马小春", "小春"): ["YuzuSoft",5],
    ("在原七海", "七海"): ["YuzuSoft",6],
    ("派蒙"): ["Genshin",0],
    ("凯亚"): ["Genshin",1],
    ("安柏"): ["Genshin",2],
    ("丽莎"): ["Genshin",3],
    ("琴"): ["Genshin",4],
    ("香菱"): ["Genshin",5],
    ("枫原万叶"): ["Genshin",6],
    ("迪卢克"): ["Genshin",7],
    ("温迪"): ["Genshin",8],
    ("可莉"): ["Genshin",9],
    ("早柚"): ["Genshin",10],
    ("托马"): ["Genshin",11],
    ("芭芭拉"): ["Genshin",12],
    ("优菈"): ["Genshin",13],
    ("云堇"): ["Genshin",14],
    ("钟离"): ["Genshin",15],
    ("魈"): ["Genshin",16],
    ("凝光"): ["Genshin",17],
    ("雷电将军"): ["Genshin",18],
    ("北斗"): ["Genshin",19],
    ("甘雨"): ["Genshin",20],
    ("七七"): ["Genshin",21],
    ("刻晴"): ["Genshin",22],
    ("神里绫华"): ["Genshin",23],
    ("戴因斯雷布"): ["Genshin",24],
    ("雷泽"): ["Genshin",25],
    ("神里绫人"): ["Genshin",26],
    ("罗莎莉亚"): ["Genshin",27],
    ("阿贝多"): ["Genshin",28],
    ("八重神子"): ["Genshin",29],
    ("宵宫"): ["Genshin",30],
    ("荒泷一斗"): ["Genshin",31],
    ("九条裟罗"): ["Genshin",32],
    ("夜兰"): ["Genshin",33],
    ("珊瑚宫心海"): ["Genshin",34],
    ("五郎"): ["Genshin",35],
    ("散兵"): ["Genshin",36],
    ("女士"): ["Genshin",37],
    ("达达利亚"): ["Genshin",38],
    ("莫娜"): ["Genshin",39],
    ("班尼特"): ["Genshin",40],
    ("申鹤"): ["Genshin",41],
    ("行秋"): ["Genshin",42],
    ("烟绯"): ["Genshin",43],
    ("久岐忍"): ["Genshin",44],
    ("辛焱"): ["Genshin",45],
    ("砂糖"): ["Genshin",46],
    ("胡桃"): ["Genshin",47],
    ("重云"): ["Genshin",48],
    ("菲谢尔"): ["Genshin",49],
    ("诺艾尔"): ["Genshin",50],
    ("迪奥娜"): ["Genshin",51],
    ("鹿野院平藏"): ["Genshin",52],
    ("和泉妃爱","妃爱"): ["fupomei",0],
    ("常盤華乃","常盘华乃","华乃"): ["fupomei",1],
    ("錦あすみ","锦亚澄"): ["fupomei",2],
    ("鎌倉詩桜","镰仓诗樱"): ["fupomei",3],
    ("竜閑天梨","龙闲天梨","天梨"): ["fupomei",4],
    ("和泉里"): ["fupomei",5],
    ("新川広夢","新川广梦"): ["fupomei",6],
    ("聖莉々子","圣莉莉子"): ["fupomei",7],
    ("綾地寧々b"): ["1374_epochs",0],
    ("在原七海b"): ["1374_epochs",1],
    ("小茸b"): ["1374_epochs",2],
    ("唐乐吟b"): ["1374_epochs",3],
}'

其中1374_epochs，fupomei，YuzuSoft都正常发出了语音，但是Genshin会报错加载模型失败
![QQ截图20221015135103](https://user-images.githubusercontent.com/110553307/195971279-b147918d-d1a9-4da1-acd3-816c057735e1.png)

**Comment by dpm12345** [comment]
设计之初就是仅仅只是为了发日文的语音，因此接收到的所有文字全都会转成日文，原神的角色在此可能无法运行(但是如果将包中的自动翻译关了或许可以)

然后你可以提供一下报错信息吗，我不确定是否是因为文本造成的问题

**Comment by dispina** [comment]
> 设计之初就是仅仅只是为了发日文的语音，因此接收到的所有文字全都会转成日文，原神的角色在此可能无法运行(但是如果将包中的自动翻译关了或许可以)
> 
> 然后你可以提供一下报错信息吗，我不确定是否是因为文本造成的问题

(我将信息中的qq号除首尾外替换成了qq号）

10-15 13:59:59 [SUCCESS] nonebot | OneBot V11 1qq号0 | [message.private.friend]: Message -2044913855 from 2qq号2
 "迪奥娜说你好"
10-15 13:59:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_tts_gal)
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\py39\-3.9\lib\site-packages\nonebot_plugin_tts_gal\__init__.py", line 89, in vo
icHandler
    len(hps_ms.symbols),
AttributeError: 'HParams' object has no attribute 'symbols'
10-15 13:59:59 [INFO] nonebot_plugin_gocqhttp | [1qq号0] 发送好友 2qq号2(2qq号2)  的消息: [{"type":  ... (12
04235517)
10-15 13:59:59 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_tts_gal) running complete

**Comment by dpm12345** [comment]
正如`AttributeError: 'HParams' object has no attribute 'symbols'`显示的，缺少symbols

但我看了原项目的代码，涉及到了中文的cleaner，本项目中并没有相关内容，添加了`symbols`应该也不会正常生成语音。所以，目前添加中文模型是不行的

**Comment by dispina** [comment]
> 正如所`AttributeError: 'HParams' object has no attribute 'symbols'`显示的，同样的符号
> 
> 但我原项目的，涉及到了中文的cleaner，本项目中并没有相关内容，添加了`symbols`也不会正常生成声音的代码。所以，目前添加中文模型是不行的

感谢，可以了，更新后的版本成功合成了中文语音。

**Comment by Loss-of-time** [comment]
> > 正如所`AttributeError: 'HParams' object has no attribute 'symbols'`显示的，同样的符号
> > 但我原项目的，涉及到了中文的cleaner，本项目中并没有相关内容，添加了`symbols`也不会正常生成声音的代码。所以，目前添加中文模型是不行的
> 
> 感谢，可以了，更新后的版本成功合成了中文语音。

求一下中文模型

**Comment by dpm12345** [comment]
> > > 正如所`AttributeError: 'HParams' object has no attribute 'symbols'`显示的，同样的符号
> > > 但我原项目的，涉及到了中文的cleaner，本项目中并没有相关内容，添加了`symbols`也不会正常生成声音的代码。所以，目前添加中文模型是不行的
> > 
> > 
> > 感谢，可以了，更新后的版本成功合成了中文语音。
> 
> 求一下中文模型

原模型似乎已经删除了
